### ISSUE TITLE
Pipeline CPU

### ISSUE THREAD

**Issue by chamip** [qing-2/CPU#1]
Hello,have you succeeded in pipeline CPU design?Share us,please.

**Comment by qing-2** [comment]
Today I will push it on another branch.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qing-2/CPU"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 中午11:17
收件人:&nbsp;"qing-2/CPU"<CPU@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qing-2/CPU] Pipeline CPU (#1)





 
Hello,have you succeeded in pipeline CPU design?Share us,please.

**Comment by chamip** [comment]
Thank you!
